import { Document, isMap, parseDocument } from "yaml";

/**
 * Shared byte-exact frontmatter split/parse primitives used by both
 * `sourceProjection.ts` (read-only hashing) and `frontmatterEngine.ts`
 * (mutation). Mirrors `split_frontmatter` in python/mindmap.py: the
 * frontmatter block is only recognized when the document opens with `---`
 * and a matching closing `---` line follows; anything else (no
 * frontmatter, unterminated block) is treated as body-only, exactly like
 * the Python oracle.
 */
export interface SplitFrontmatter {
  frontmatterRaw: string | null;
  body: string;
}

export function splitFrontmatter(text: string): SplitFrontmatter {
  if (!text.startsWith("---")) {
    return { frontmatterRaw: null, body: text };
  }
  const lines = text.split(/(?<=\n)/);
  if (lines.length < 2) {
    return { frontmatterRaw: null, body: text };
  }
  let offset = lines[0].length;
  for (let index = 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (line.trim() === "---") {
      const frontmatterRaw = text.slice(lines[0].length, offset);
      const body = text.slice(offset + line.length);
      return { frontmatterRaw, body };
    }
    offset += line.length;
  }
  return { frontmatterRaw: null, body: text };
}

/** The note's dominant line-ending convention, used only to shape newly generated bytes -- never to rewrite bytes copied verbatim from the original text. */
export function detectNewline(text: string): "\r\n" | "\n" {
  return text.includes("\r\n") ? "\r\n" : "\n";
}

export interface FrontmatterKeyRange {
  key: string;
  /** Byte offset (into the frontmatter-only substring) where the key token starts. */
  start: number;
  /** Byte offset where this key's block ends: the value plus any trailing same-line comment and line terminator, i.e. up to (exclusive of) the next key or end of frontmatter. */
  end: number;
  /**
   * Byte offset separating the key's own `key: value` content from a
   * trailing same-line comment. Equal to `end` when the pair has no
   * trailing comment (the common case; `[start, end)` is then one
   * indivisible, freely replaceable/removable block, unchanged from before
   * this field existed). When a trailing comment IS present, `[start,
   * commentBoundary)` is the replaceable/removable `key: value` content and
   * `[commentBoundary, end)` is the comment plus its original leading
   * whitespace and line terminator, exactly as written -- callers that
   * update or remove this key must preserve `[commentBoundary, end)`
   * byte-for-byte rather than discarding it, so a user's trailing comment
   * on a managed key survives regeneration/removal instead of being
   * silently deleted.
   *
   * A comment on a leading/standalone line (before this key, or after a
   * multi-line block value before the next key) is never inside any key's
   * `[start, end)` range in the first place -- it lives in the untouched
   * gap between two ranges -- so it already survives without needing this
   * field at all.
   */
  commentBoundary: number;
}

export type ParsedFrontmatterKeys =
  | { ok: true; ranges: FrontmatterKeyRange[] }
  | { ok: false; reason: string };

/**
 * Semantic replacement for the Checkpoint-1 top-level-key regex heuristic:
 * uses the real YAML parser (via `yaml`'s Document API and its per-node
 * `range` offsets, which extend through same-line trailing comments) to
 * find exactly where each top-level key's block starts and ends in the
 * original frontmatter bytes. Byte ranges not covered by any returned key
 * (leading/trailing comments, blank lines, gaps between keys) are never
 * touched by a caller that only replaces/removes matched ranges.
 *
 * Returns `ok: false` for genuinely malformed YAML (parse errors, duplicate
 * keys -- `uniqueKeys` is on) or frontmatter whose root is not a mapping.
 * An empty/whitespace-only frontmatter block is valid (equivalent to `{}`)
 * and returns an empty range list.
 */
export function parseFrontmatterKeyRanges(frontmatterRaw: string): ParsedFrontmatterKeys {
  if (frontmatterRaw.trim() === "") {
    return { ok: true, ranges: [] };
  }
  const doc = parseDocument(frontmatterRaw, { keepSourceTokens: true, uniqueKeys: true });
  if (doc.errors.length > 0) {
    return { ok: false, reason: doc.errors[0]?.message ?? "YAML parse error." };
  }
  if (doc.contents === null || doc.contents === undefined) {
    return { ok: true, ranges: [] };
  }
  if (!isMap(doc.contents)) {
    return { ok: false, reason: "Frontmatter must be a YAML mapping." };
  }
  const ranges: FrontmatterKeyRange[] = [];
  for (const pair of doc.contents.items) {
    const keyNode = pair.key as { value?: unknown; range?: [number, number, number] } | null;
    if (!keyNode || !Array.isArray(keyNode.range)) continue;
    const key = String(keyNode.value);
    const start = keyNode.range[0];
    const valueNode = pair.value as { range?: [number, number, number]; comment?: string } | null;
    const end = valueNode && Array.isArray(valueNode.range) ? valueNode.range[2] : keyNode.range[2];
    const hasTrailingComment = !!(valueNode && typeof valueNode.comment === "string");
    const commentBoundary = hasTrailingComment && valueNode?.range ? valueNode.range[1] : end;
    ranges.push({ key, start, end, commentBoundary });
  }
  ranges.sort((a, b) => a.start - b.start);
  return { ok: true, ranges };
}

/**
 * Serializes a single `key: value` line (plus trailing newline) using the
 * same style ruamel's round-trip dumper produces: 2-space mapping/sequence
 * indent, single-quoted scalars when quoting is required, and no line
 * wrapping. Always LF-terminated; callers convert to the target newline
 * convention via `toNoteNewline`.
 */
export function serializeFrontmatterKeyLine(key: string, value: unknown): string {
  const doc = new Document();
  doc.contents = doc.createNode({ [key]: value });
  return doc.toString({ singleQuote: true, lineWidth: 0 });
}

/** Converts LF-generated text (from `serializeFrontmatterKeyLine`) to the note's own newline convention. A no-op for `"\n"`. */
export function toNoteNewline(text: string, newline: "\r\n" | "\n"): string {
  return newline === "\n" ? text : text.replace(/\n/g, newline);
}

/**
 * Reassembles a full note document with its frontmatter block byte-exactly
 * preserved and its body replaced by `newBody`. `text` must already have a
 * frontmatter block (as `updateFrontmatter` always produces); the note's
 * newline convention is used for the separator between the closing `---`
 * and `newBody` when `newBody` doesn't already start with one.
 */
export function replaceBody(text: string, newBody: string): string {
  const { frontmatterRaw } = splitFrontmatter(text);
  if (frontmatterRaw === null) {
    return newBody;
  }
  const newline = detectNewline(text);
  const bodySeparator = newBody.startsWith(newline) ? newBody : `${newline}${newBody}`;
  return `---${newline}${frontmatterRaw}---${bodySeparator}`;
}
